[package]
name = "s2_actix"
version = "0.1.0"
edition = "2024"
default-run = "manage_server"

[dependencies]
actix-web = "4.11.0"
serde = {version = "1.0.219", features = ["derive"]}
chrono = {version = "0.4.41", features = ["serde"]}

[[bin]]
name = "manage_server"